services:
  bizeps-entertainment:
    image: bizeps-entertainment
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bizeps-entertainment-1
    healthcheck:
      test: [
        "CMD-SHELL",
        "wget -qO- http://127.0.0.1:80/ || exit 1"
      ]
      interval: 10s
      timeout: 20s
      retries: 3